name: Setup toolchain
description: Set up Node.js and cache PureScript build artifacts
runs:
  using: composite
  steps:
    - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: 'lts/*'
        cache: 'npm'
      shell: bash
    - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: |
          .spago
          output
        key: ${{ runner.os }}-spago-${{ hashFiles('**/spago.lock') }}-${{ hashFiles('**/spago.yaml') }}
        restore-keys: |
          ${{ runner.os }}-spago-
